import random

# Base search terms
base_searches = [
    "weather today",
    "latest news",
    "funny cat videos",
    "how to cook pasta",
    "bitcoin price",
    "movies near me",
    "current time in Tokyo",
    "translate hello to Spanish",
    "nearest coffee shop",
    "today's horoscope",
    "recipe for pancakes",
    "how to tie a tie",
    "fastest car in the world",
    "cheap flights to Japan",
    "photos of puppies",
    "best gaming laptop 2025",
    "top songs right now",
    "easy workout at home",
    "NBA scores",
    "meaning of life",
    "best smartphone 2025",
    "top tourist destinations",
    "how to lose weight fast",
    "funny memes",
    "DIY home decor",
    "stock market today",
    "space news",
    "football scores",
    "healthy breakfast ideas",
    "world map",
    "best anime of all time",
    "guitar chords for beginners",
    "how to grow tomatoes",
    "make money online",
    "cheap hotels near me",
    "YouTube trending",
    "history of the internet",
    "best free VPN",
    "new technology gadgets",
    "popular baby names",
    "current gold price",
    "how to bake cookies",
    "coding tutorials",
    "python programming",
    "fastest animals on earth",
    "AI news",
    "car reviews",
    "how to meditate",
    "fun riddles",
    "random facts",
    "time in New York",
    "train schedule",
    "learn Spanish online",
    "best horror movies",
    "weather tomorrow",
    "NBA draft 2025",
    "Olympics 2025 updates",
    "how to draw a cat",
    "science experiments",
    "best pizza near me",
    "universe size",
    "biggest countries by area",
    "how to make sushi",
    "book recommendations",
    "best beaches in the world",
    "how to change a tire",
    "flight tracker",
    "dog training tips",
    "cheap second hand cars",
    "famous quotes",
    "mountain climbing tips",
    "top video games",
    "how to play chess",
    "computer repair tips",
    "fun brain teasers",
    "music festivals 2025",
    "camera buying guide",
    "fitness motivation",
    "budget travel tips",
    "learn coding for free",
    "how to make coffee",
    "top restaurants near me",
    "best PC games 2025",
    "how to save money",
    "gardening tips",
    "volcano facts",
    "biggest cities in the world",
    "solar system planets",
    "train your memory",
    "healthy lunch recipes",
    "AI image generator",
    "space exploration timeline",
    "best books 2025",
    "best places to retire",
    "famous landmarks",
    "history of World War 2",
    "learn guitar online",
    "how to fix WiFi issues",
    "cat breeds list",
    "coffee benefits",
    "Credits By Christian Geronimo",

]

# Variations
variations = [
    "",
    " near me",
    " 2025",
    " online",
    " free",
    " tutorial",
    " now",
    " update",
    " live",
    " for beginners",
    " step by step",
    " full guide",
    " in my area",
    " with pictures",
    " easy method",
    " fast",
    " best tips",
    " today only",
    " cheap",
    " without registration",
    " top rated",
    " PDF",
    " download",
    " examples",
    " review",
    " explained",
    " new",
    " trending",
    " best choice",
    " for kids",
    " for adults",
    " near airport",
    " nearby",
    " free download",
    " without login",
    " premium",
    " schedule",
    " in the world",
    " near city center",
    " guide",
    " news",
    " details",
    " info",
    " for work",
    " at home",
    " DIY",
    " hacks",
    " ideas",
    " best deals",
    " top 10",
    " comparison",
    " 2024",
    " HD",
    " free trial",
    " popular",
    " quiz",
    " challenge",
    " list",
    " ranking",
    " cheapest",
    " open now",
    " local",
    " nearby shop",
    " this week",
    " this month",
    " special offer",
    " coupon",
    " voucher",
    " discount",
    " recipes",
    " with video",
    " on YouTube",
    " playlist",
    " history",
    " map",
    " chart",
    " stats",
    " facts",
    " pictures",
    " wallpaper",
    " meme",
    " blog",
    " forum",
    " FAQ",
    " how to",
    " tips and tricks",
    " review 2025",
    " demo",
    " case study",
    " quick start",
    " short version",
    " full version",
    " sample",
    " latest",
    " upcoming",
    " collection",
    " directory",
]

# Generate 500,000 random searches
searches_large = []
for _ in range(500_000):
    base = random.choice(base_searches)
    variation = random.choice(variations)
    searches_large.append(f"{base}{variation}".strip())

# Save to a file in the same directory as the script
with open("random_searches_500k.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(searches_large))

print("random_searches_500k.txt has been created successfully!")
